// <auto-generated />
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Data.Migrations
{
    [DbContext(typeof(EntityFrameworkDbContext))]
    [Migration("20221107085927_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Core.Entities.AggregatedData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("OBJ_GV_TIPAS")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OBJ_NUMERIS")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OBT_PAVADINIMAS")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PL_T")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PMinus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PPlus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TINKLAS")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AggregatedDatas");
                });
#pragma warning restore 612, 618
        }
    }
}
